# This is  not the installation of nodejs
# This is an image that already have nodejs installed in a linux
# The alpine extension is a lightweight version of linux
FROM node:alpine 
COPY . /app
WORKDIR /app
CMD node app.js
